<table <?php foreach($attributes as $key => $value) echo $key . '="' . $value . '"'?>>
    <thead>
        <tr>
            <?php foreach ($columns as $column): ?>
                <th><?= $column['label']; ?></th>
            <?php endforeach; ?>
        </tr>
    </thead>
    <tbody>
        <?php if (isset($items) && count($items) > 0) :?>
            <?php foreach ($items as $item): ?>
                <tr>
                    <?php foreach ($item as $key => $value): ?>
                        <?php if (is_string($key)): ?>
                            <td><?= $value; ?></td>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </tbody>
</table>

<?php
$this->headScript()->appendScript(<<<EOF
$(document).ready(function () {
    $('#{$attributes['id']}').dataTable({$optionsEncoded});
});
EOF
);
