<table id="<?= $id; ?>">
    <thead>
        <tr>
            <?php foreach ($columns as $column): ?>
                <th><?= $column['label']; ?></th>
            <?php endforeach; ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($items as $item): ?>
            <tr>
                <?php foreach ($item as $key => $value): ?>
                    <?php if (is_string($key)): ?>
                        <td><?= $value; ?></td>
                    <?php endif; ?>
                <?php endforeach; ?>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php
$this->headScript()->appendScript(<<<EOF
$(document).ready(function () {
    $('#{$id}').dataTable({$optionsEncoded});
});
EOF
);